### ISSUE TITLE
'FabricHomes' (fabrichomes) 2.2.0 requires any version of fabric-permissions-api-v0, which is installed already.

### ISSUE THREAD

**Issue by Kerberos91** [CodedSakura/FabricHomes#18]
This is what it tells me after i try to run it with just FabricHomes and fabric-api-0.46.4+1.18

net.fabricmc.loader.impl.FormattedException: net.fabricmc.loader.impl.discovery.ModResolutionException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Install fabric-permissions-api-v0, any version.
Unmet dependency listing:
	 - Mod 'FabricHomes' (fabrichomes) 2.2.0 requires any version of fabric-permissions-api-v0, which is missing!
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:189)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:142)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:71)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: net.fabricmc.loader.impl.discovery.ModResolutionException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Install fabric-permissions-api-v0, any version.
Unmet dependency listing:
	 - Mod 'FabricHomes' (fabrichomes) 2.2.0 requires any version of fabric-permissions-api-v0, which is missing!
	at net.fabricmc.loader.impl.discovery.ModResolver.findCompatibleSet(ModResolver.java:159)
	at net.fabricmc.loader.impl.discovery.ModResolver.resolve(ModResolver.java:45)
	at net.fabricmc.loader.impl.FabricLoaderImpl.setup(FabricLoaderImpl.java:224)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:187)
	... 3 more

**Comment by CodedSakura** [comment]
You need to also add https://github.com/lucko/fabric-permissions-api/releases, but i'm planning on making it optional

**Comment by CodedSakura** [comment]
well, i just released 2.2.1, in which fabric-permission-api is optional low
