### ISSUE TITLE
21w07a sethome crash

### ISSUE THREAD

**Issue by SSZX866** [CodedSakura/FabricHomes#3]
---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 21-3-5 下午1:00
Description: Exception in server tick loop

java.lang.NoClassDefFoundError: dev/onyxstudios/cca/api/v3/entity/EntityComponentInitializer
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.security.SecureClassLoader.defineClass(Unknown Source)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:163)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at eu.codedsakura.fabrichomes.FabricHomes.homeSet(FabricHomes.java:140)
	at eu.codedsakura.fabrichomes.FabricHomes.lambda$null$3(FabricHomes.java:69)
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:262)
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:176)
	at net.minecraft.class_2170.method_9249(class_2170.java:249)
	at net.minecraft.class_3244.method_14370(class_3244.java:1239)
	at net.minecraft.class_3244.method_31286(class_3244.java:1223)
	at net.minecraft.class_3244.method_12048(class_3244.java:1206)
	at net.minecraft.class_2797.method_12115(class_2797.java:36)
	at net.minecraft.class_2797.method_11054(class_2797.java:9)
	at net.minecraft.class_2600.method_11072(class_2600.java:21)
	at net.minecraft.class_3738.run(class_3738.java:18)
	at net.minecraft.class_1255.method_18859(class_1255.java:144)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:763)
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:159)
	at net.minecraft.class_1255.method_16075(class_1255.java:118)
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:745)
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:739)
	at net.minecraft.class_1255.method_18857(class_1255.java:127)
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:724)
	at net.minecraft.server.MinecraftServer.handler$zep000$modifiedRunLoop(MinecraftServer.java:3319)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:653)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:259)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: dev.onyxstudios.cca.api.v3.entity.EntityComponentInitializer
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at net.fabricmc.loader.launch.server.InjectingURLClassLoader.loadClass(InjectingURLClassLoader.java:56)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:168)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 30 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 21w07a
	Minecraft Version ID: 21w07a
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_251, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 4650604088 bytes (4435 MB) / 6794772480 bytes (6480 MB) up to 7635730432 bytes (7282 MB)
	CPUs: 6
	JVM Flags: 5 total; -Xms4G -Xmx8G -Xverify:none -XX:+UseParallelOldGC -XX:MaxInlineSize=420
	Fabric Mods: 
		autoconfig1u: Auto Config v1 Updated 3.3.1
		carpet: Carpet Mod in Fabric 1.4.27
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-config2: Cloth Config v4 4.8.3
		fabric: Fabric API 0.31.0+1.17
		fabric-api-base: Fabric API Base 0.2.1+524a2e8580
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.4+1eb2670e80
		fabric-command-api-v1: Fabric Command API (v1) 1.1.0+f9d6353a80
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+92519afa80
		fabric-containers-v0: Fabric Containers (v0) 0.1.11+524a2e8580
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.1+92519afa80
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.3+92519afa80
		fabric-dimensions-v1: fabric-dimensions-v1 2.0.6+524a2e8580
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.0.3+92519afa80
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.4+92519afa80
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+92519afa80
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.6+92519afa80
		fabric-item-api-v1: Fabric Item API (v1) 1.2.3+36b77c3e80
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.3+92519afa80
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.3+40e100eb80
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.4+92519afa80
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+92519afa80
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.4+40e100eb80
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.9+40e100eb80
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+92519afa80
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.10.5+40e100eb80
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.3+92519afa80
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+92519afa80
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.5+92519afa80
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+92519afa80
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.4+1eb2670e80
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.6+40e100eb80
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.5+1eb2670e80
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.2+92519afa80
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.9+36b77c3e80
		fabrichomes: FabricHomes 0.1.2
		fabricloader: Fabric Loader 0.11.1
		falling_tree: FallingTree 2.5.1
		java: Java HotSpot(TM) 64-Bit Server VM 8
		minecraft: Minecraft 1.17-alpha.21.7.a
		ring_of_enderchest: Ring of Enderchest 1.1.3
		ring_of_growth: Ring Of Growth 1.1.3
		ring_of_miner: Ring Of Miner 1.2.2
	Player Count: 1 / 20; [class_3222['Tianji'/95, l='ServerLevel[world]', x=240.85, y=63.00, z=12952.05]]
	Data Packs: vanilla, Fabric Mods
	Is Modded: Definitely; Server brand changed to 'fabric'
	Type: Dedicated Server (map_server.txt)

**Comment by CodedSakura** [comment]
This seems to be a problem with a dependency, Cardinal Components, which i use to store the homes. That means i can't do much to fix this issue without releasing a 1.17 specific version (which i'm hesitant to do)

**Comment by ItsMCB** [comment]
> This seems to be a problem with a dependency, Cardinal Components, which i use to store the homes. That means i can't do much to fix this issue without releasing a 1.17 specific version (which i'm hesitant to do)

I was hoping to use this plugin for my snapshot server too. I understand that making a 1.17 version might not be what you'd want to do right now though.

**Comment by CodedSakura** [comment]
fixed in v2.0.0
