### ISSUE TITLE
Interdimensional teleport endless loading

### ISSUE THREAD

**Issue by xManuwa** [CodedSakura/FabricHomes#4]
When I am in the Nether and enter /home, i get an error in the server-console and the game does not stop loading until I close Minecraft or kick myself with the help of the console. However, it didn't occur everytime when I tried to recreate it but only sometimes.

I tried to recreate it and figure out what is causing it. I got the same error once again whilst trying but I don't know why and when it happens.

The error I got looked like this:
```
Exception in thread "Timer-186" [10:10:26] [Timer-186/INFO]: [STDERR]: java.lang.IllegalStateException: Removing entity while ticking!
[10:10:26] [Timer-186/INFO]: [STDERR]:  at net.minecraft.class_3218.method_18774(class_3218.java:942)
[10:10:26] [Timer-186/INFO]: [STDERR]:  at net.minecraft.class_3218.method_18770(class_3218.java:958)
[10:10:26] [Timer-186/INFO]: [STDERR]:  at net.minecraft.class_3222.method_14251(class_3222.java:1440)
[10:10:26] [Timer-186/INFO]: [STDERR]:  at eu.codedsakura.fabrichomes.FabricHomes.lambda$homeInit$13(FabricHomes.java:127)
[10:10:26] [Timer-186/INFO]: [STDERR]:  at eu.codedsakura.mods.TeleportUtils$1.run(TeleportUtils.java:47)
[10:10:26] [Timer-186/INFO]: [STDERR]:  at java.base/java.util.TimerThread.mainLoop(Timer.java:556)
[10:10:26] [Timer-186/INFO]: [STDERR]:  at java.base/java.util.TimerThread.run(Timer.java:506)
```

**Comment by CodedSakura** [comment]
Yea, this is a know bug to me, but i don't have an idea of how to fix that or what even causes that
